
export const Endpoints = {
    Businesses: "/data-api/v1/businesses",
    CropZones: "/data-api/v1/crop_zones",
    Daily: "/data-api/v1/services/get_observations/daily_interpolated",
    DailyMultiple: "/data-api/v1/services/get_observations/multiple_daily_interpolated",
    Farms: "/data-api/v1/farms",
    Fields: "/data-api/v1/fields",
    FieldBoundary: "/data-api/v1/field_boundaries",
    Fieldboundaries: "/data-api/v1/services/field_boundary/business/",
    Normal: "/data-api/v1/services/get_observations/normal",
    NormalMultiple: "/data-api/v1/services/get_observations/normal_multiple",
    GrowthStages: "/data-api/v1/services/weather/growth_stages",
    GrowthStages2: "/data-api/v1/services/weather/growth_stages_2",
    plantingSummaryStats: "/data-api/v1/services/map_layer_catalog/planting_stats/business",
    WeatherCache: "/data-api/v1/weather_cache",
    baseFeatureFlags: "/data-api/v1/services/feature_flag/Compass",
    defaultFeatureFlags: '/data-api/v1/services/feature_flag/Compass/enabled',
    myFeatureFlags: '/data-api/v1/services/feature_flag/Compass/me',
    feedback: '/data-api/v1/feedback',
    userProfile: '/data-api/v1/user_profiles',
    centroids: '/data-api/v1/services/field_boundary/centroids',
    NewNormal: '/weather-api/v0/daily_interpolated_norms',
    NewDaily: '/weather-api/v0/daily_interpolated',
    SearchItems: '/data-api/v1/services/preferences/compass/searchItems',
    UserPermissions: '/data-api/v1/services/user_permission/permissions_with_relationships',
    activityRecord: '/data-api/v1/activity_record',
    preferences: '/data-api/v1/services/preferences/compass',
    opSummary: '/data-api/v1/services/op_summary'
}
